/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\HorribleRoom.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HorribleRoom(props) {
  const { nodes, materials } = useGLTF('/models/HorribleRoom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor.geometry} material={materials.TileFloor} />
      <mesh geometry={nodes.FrontWall.geometry} material={materials.Wall} />
      <mesh geometry={nodes.SideWall.geometry} material={materials.Wall} />
      <mesh geometry={nodes.SideDesk.geometry} material={materials.DeskBlack} />
      <mesh geometry={nodes.Desk.geometry} material={materials.DeskBlack} />
      <group position={[-13.279, 0, 0]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.DeskBlack} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.TileFloor} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials.Wall} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/HorribleRoom.glb')
