name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          uv-version: '0.2.10'

      - name: Install dependencies
        run: npm install

      - name: Build Jupyter Book
        run: npm run build:book

      - name: List files in jupyter-books
        run: ls -R jupyter-books

      - name: Copy Jupyter Book to public
        run: npm run copy:book

      - name: Build Vite application
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
